blank_issues_enabled: false
name: New Feature
description: 新機能のアイデア関するIssue
labels: ["enhancement"]
body: 
  - type: markdown
    attributes:
      value: |
        当プロジェクトへの参加ありがとうございます。以下の情報を記入してください。
  
  - type: textarea
    attributes: 
      label: 新機能の説明
      description: 追加したい機能はどのような機能か、記入してください。
      palceholder: |
        オプションとして...を追加したいと思っています。
        これは...の働きをします。
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: リクエストの理由
      description: なぜ追加したいのか、そう思った理由を記入してください。
      palceholder: |
        現状、このコマンドは...のような働きをしますが、このコマンドだと...のような問題点があります。
        この場合、...のようなオプションがあれば、この問題を解決できると考えています。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 実装の提案
      description: もし機能の実装の提案があれば記入してください。必須ではありません。
      palceholder: |
        現状の`...`構造体に`...`フィールドを追加すれば良いと思います。
    validations:
      required: false